// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlgkhooljpvnbqfieobw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZ2tob29sanB2bmJxZmllb2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjU4MzAsImV4cCI6MjA2MzM0MTgzMH0.bz5peweo_ZzlWCIZKM9Hi7gdAqb-1PioZ9z78RSFWdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);